# Generated by Django 2.1.5 on 2019-01-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.CharField(choices=[('d', 'Rascunho'), ('p', 'Publicado')], default=-1.0, max_length=1),
            preserve_default=False,
        ),
    ]
