# Generated by Django 2.1.5 on 2019-01-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
